[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[window]
decorations = "full"
opacity = 1

[window.padding]
x = 6
y = 6

[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"

